### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by DominiqueMakowski** [Tam-Pham/HRVStructure#2]
So after OHBM and meeting some people from the community, we should really push this forward.

I am tagging @danibene who expressed interest in helping out here and @sangfrois might find useful stuff as well.

## Roadmap for paper

- [ ] Find and add more data (I would look openNeuro, also, best would be to gain access to big banks like UK biobank but the application process looks complicated. Francois also mentioned neuromod from which we could get some PPG data?)
- [ ] Add new HRV indices that we added since
  - Try the possibility of a new metric for the frequency domain analog to the 1/f slope used in EEG (foof package) to see how it compares to LF/HF
- [ ] add UMAP as part of the dimension reduction if we don't have it already (and maybe make a nice plot out of it as it's a trendy method)
 

## Side projects / side papers  (?)

- [ ] Have this set of databases used easily re-usable with a good documentation on how to download it (will be of interest to the physiopy community)
- [ ] A useful and easy to do side study would be to, on the same data base, compute optimal complexity parameters (delay, embedding & threshold) on the raw heart heart rate and maybe analyze as a function of mean heart rate.
- [ ] Use this metadatabase for quality control validation (?) @sangfrois

We could schedule a meeting to refresh ourselves and the new potential collaborators about what we've done so far, and lay out the work ahead

**Comment by sangfrois** [comment]
Excellent! Thank you for getting the ball rolling! This will surely help [CNeuroMod](cneuromod.ca) accelerate processing, validating and sharing the phys data. 

We were thinking of adding the physiology to our "alpha" release sometime mid-august with BIDSified raw data. That would facilitate data access.

I'm making myself a note to look into the most efficient way for you @DominiqueMakowski to get access. Either through a DTA or using the three subjects' fully open data through [CONP](https://portal.conp.ca/dataset?id=projects/cneuromod). CONP would be more efficient at the expense of missing three subjects (out of 6). Not everyone agreed yet.

PPG is certainly of stable quality, but we could perhaps add our ECG as a bonus if everything goes according to plan?

Super down to look into other clustering algorithms as well (other than UMAP, PCA and t-SNE?). Also, do I recall correctly that you were running the statistical analysis using R? If yes, I will need a run-through cause I'm totally not familiar.

In terms of meeting, I have a feeling we could probably push that at least until I get data access settled? So next month probably.

Let's Marie Ève Picard to the loop, and Basile Pinsard perhaps? (He's the data manager)

Peace my friends.

**Comment by danibene** [comment]
Thank you for including me in this discussion, very excited!

I think having a framework to load a meta-database would be a great resource for future analyses, including quality control - I wonder if we could adapt existing code used to evaluate ECG with open data e.g.: https://github.com/DeepPSP/torch_ecg/tree/0caadc007041e9b4b84f536b4b73000105c0806c/torch_ecg/databases

**Comment by Tam-Pham** [comment]
hi @sangfrois and @danibene 
Excited to be working together to revive and advance this project!

> We could schedule a meeting to refresh ourselves and the new potential collaborators about what we've done so far, and lay out the work ahead

Second this!

I also added [reviewer's comments](https://github.com/Tam-Pham/HRVStructure/blob/main/docs/reviewers_comments.docx) for the previous submission so that we can address in this revision

**Comment by DominiqueMakowski** [comment]
> I think having a framework to load a meta-database would be a great resource for future analyses

We currently have the `data/` [folder](https://github.com/neuropsychology/NeuroKit/tree/master/data) in NK with the code to download most of the databases used so far. 

However, it could be cool to somehow assemble that in like a function that can download databases locally using the same interface and tidy them up so that we can easily loop through them, load the signals, get some metainfo (sampling rate, database name, reference, recording condition (e.g., resting state, task, ambulatory, sleep...), participants (healthy young, ...)), extract the stuff we want (in our first case, HRV indices), and eventually delete the database after usage.

```python
import NeuroKit2 as nk

def extract_stuff(db_path=""):
   meta_info = read_csv(db_path + "/path")
   ...
   return indices

# ---- workflow example
for db in ["fantasia", "mit", "ludb", "neuromod"]:
    nk.database_download(db)
    extract_stuff(db)
    nk.database_remove(db)
```

Note: at least for openneuro data, it's unfortunately not possible [for now](https://github.com/hoechenberger/openneuro-py/issues/94) to stream participant by participant and do the processing in memory, hence the above proposition of having separate functions to download and delete (critical for someone like me who likes to live with only a few MOs left on my hardrive).
